USE [master]
GO

/****** Object:  Database [Lawyer]    Script Date: 27.08.2021 17:26:59 ******/
CREATE DATABASE [Lawyer]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Lawyer', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLSRV2017\MSSQL\DATA\Lawyer.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Lawyer_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLSRV2017\MSSQL\DATA\Lawyer_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Lawyer].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Lawyer] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Lawyer] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Lawyer] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Lawyer] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Lawyer] SET ARITHABORT OFF 
GO

ALTER DATABASE [Lawyer] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Lawyer] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Lawyer] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Lawyer] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Lawyer] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Lawyer] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Lawyer] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Lawyer] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Lawyer] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Lawyer] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Lawyer] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Lawyer] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Lawyer] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Lawyer] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Lawyer] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Lawyer] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Lawyer] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Lawyer] SET RECOVERY FULL 
GO

ALTER DATABASE [Lawyer] SET  MULTI_USER 
GO

ALTER DATABASE [Lawyer] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Lawyer] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Lawyer] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Lawyer] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Lawyer] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Lawyer] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Lawyer] SET  READ_WRITE 
GO


